### ISSUE TITLE
profile code with samply

### ISSUE THREAD

**Issue by tristanpoland** [Stars-Beyond/Horizon-Community-Edition#60]
![Image](https://github.com/Stars-Beyond/Horizon-Community-Edition/assets/75321465/40239ec2-63be-4924-aeb1-1d3cf73e0321)

a lot of time is being spent iterating through a Vec

**Comment by WilliamAnimate** [comment]
looking into it further, this code seems to be part of terraforge::space::simulate

there are two ways i can think of fixing this:
[use what instructions the CPU is capable of](https://github.com/Stars-Beyond/TerraForge/issues/1)
parallelize the iterator with [rayon](https://crates.io/crates/rayon)

of course, these can be combined.

**Comment by WilliamAnimate** [comment]
> looking into it further, this code seems to be part of terraforge::space::simulate
> 
> there are two ways i can think of mitigating this:
> [use what instructions the CPU is capable of](https://github.com/Stars-Beyond/TerraForge/issues/1), so it spends less time in the iterator (in the `update_position` function)
> parallelize the iterator with [rayon](https://crates.io/crates/rayon)
> 
> of course, these can be combined.

![rn_image_picker_lib_temp_0e4ae1ea-4db2-44cc-862c-7605aa33cf71.jpg](https://github.com/Stars-Beyond/Horizon-Community-Edition/assets/75321465/19134c31-7528-4dc8-8097-ebd26c99a80a)

sizable performance improvement on my end from commit [273b986](https://github.com/Stars-Beyond/TerraForge/commit/273b9867c256eb9569d58b5c32c9a951684e83c7) on my machine. for reference, KT used to take 1.6 seconds

**Comment by tristanpoland** [comment]
@WilliamAnimate This ended up being merged correct?

**Comment by WilliamAnimate** [comment]
> @WilliamAnimate This ended up being merged correct?

yes, however, [this commit](https://github.com/Stars-Beyond/TerraForge/commit/bb3a3d829bc2a171ba20f1b94d10015b68a93cfa#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L21) removes the space::simulate call which means my new code isn't being called.

**Comment by tristanpoland** [comment]
> > @WilliamAnimate This ended up being merged correct?
> 
> yes, however, [this commit](https://github.com/Stars-Beyond/TerraForge/commit/bb3a3d829bc2a171ba20f1b94d10015b68a93cfa#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L21) removes the space::simulate call which means my new code isn't being called.

Thanks bud, ill take a look into getting that re-added later on in Terraforge's development, Odds are the orbit functionality will be migrated
