### ISSUE TITLE
lock stdout and buffer it for faster printing

### ISSUE THREAD

**Issue by tristanpoland** [Stars-Beyond/Horizon-Community-Edition#62]

**Comment by WilliamAnimate** [comment]
tl;dr we're multithreaded and we're going to need to reimplement the mutex to implement this effectively, so don't put println! in hot loops

yeah, this is a multithreaded context.

it would be very hard to lock stdout and do our stuff to it, without introducing the same lock/unlock problem.

not to mention the tracing::info macro likely calls println! internally (or some sort of it), and reimplementing said macro is out of scope for this project

so, just try to not put println! calls in hot loops, and everyone will be happy
